import puppeteer from 'puppeteer';
const url = process.argv[2];
const out = process.argv[3];
const browser = await puppeteer.launch();
const page = await browser.newPage();
await page.setViewport({ width: 420, height: 1400, deviceScaleFactor: 2 });
await page.goto(url, { waitUntil: 'networkidle0', timeout: 90000 });
await new Promise(r => setTimeout(r, 3000));
await page.screenshot({ path: out, fullPage: false });
await browser.close();
console.log('saved', out);
